title: Arthur Prigent # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD student at <a href="https://www.linkedin.com/in/example/">GEOMAR Helmholtz Centre for Ocean Research Kiel</a>

  <a href="https://www.linkedin.com/in/arthur-prigent/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
