title: Arthur Prigent # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD student at <a href="https://www.geomar.de/en/">GEOMAR Helmholtz Centre for Ocean Research Kiel</a>

theme: jekyll-theme-minimal
google_analytics: G-Q1B2B0RWW1 # your Google Analytics tracking ID here


#social_links:
#    twitter: jekyllrb
#    github:  jekyll

plugins:
# - jekyll-feed
 - jekyll-seo-tag
#
